zuul:
  ignored-services: '*'
  routes:
    servicea:
      path: /**
      serviceId: servicea
    eureka:
      path: /dashboard/**
      url: http://descovery:8761/

  hystrix:
     command:
       default:
         execution:
           isolation:
             thread:
               timeoutInMilliseconds: 60000

